#!/bin/bash

function installSystemFolders {
  if [ ! -d "$(pwd)/mntdir/sites" ]; then
     mkdir $(pwd)/mntdir/sites
     mkdir $(pwd)/mntdir/.system
     mkdir $(pwd)/mntdir/.system/incoming
     mkdir $(pwd)/mntdir/.system/history
     mkdir $(pwd)/mntdir/.system/logs
  fi
}

installSystemFolders